name: 'Run GTO '
description:
  'Runs GTO show and populates info about triggering event in outputs.'
author: 'Iterative, Inc.'
inputs:
  show:
    description:
      'Whether to run gto show'
    default: "false"
    required: false
  history:
    description:
      'Whether to run gto history'
    default: "false"
    required: false
  print-outputs:
    description:
      'Whether to print all action outputs'
    default: "true"
    required: false
outputs:
  event:
    description: "Type of triggering event"
  name:
    description: "The name of the artifact"
  version:
    description: "The version of the artifact"
  stage:
    description: "The stage - if the events is a stage assignment"
  type:
    description: "The type of the artifact (if annotated)"
  path:
    description: "The path of the artifact (if annotated)"
  description:
    description: "The description of the artifact (if annotated)"
runs:
  using: docker
  image: "Dockerfile"
  args:
    - $GITHUB_REF
    - ${{ inputs.show }}
    - ${{ inputs.history }}
    - ${{ inputs.print-outputs }}
branding:
  icon: terminal
  color: purple
